import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen dark:bg-gray-900">
        <h1 className="text-center pt-16 text-5xl font-semibold underline dark:text-white">Welcome to KnowledgeDAO</h1>
        <h2 className="text-center pt-8 text-xl font-semibold underline dark:text-white">Publish articles on FEVM and get paid in FILCOIN</h2>
      </main>
    </div>
  );
}
